"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";

type Row = Record<string, string>;
type MetricRow = { group:string; n:number; prevalence:number; auc:number|null; sensitivity:number|null; specificity:number|null; positiveRate:number; brier:number; oeRatio:number|null; ppv:number|null; npv:number|null; fpr:number|null; fnr:number|null };
const COLORS = ["#f06d45", "#2c7a78", "#5b67b0", "#b05f84", "#8a6f38", "#557c3e"];

function seededRandom(seed:number) { let value=seed>>>0; return () => { value=(value*1664525+1013904223)>>>0; return value/4294967296; }; }
function syntheticRows():Row[] {
  const random=seededRandom(20260812), rows:Row[]=[];
  for(let i=0;i<50000;i+=1){
    const sex=i%2===0?"Female":"Male", ageBand=["45-54","55-64","65-74","75+"][i%4], ageBase=[50,60,69,80][i%4];
    const age=ageBase+Math.floor(random()*7)-3, diabetes=random()<.2?1:0, hypertension=random()<.38?1:0,smoker=random()<.19?1:0,heartFailure=random()<.09?1:0,priorMi=random()<.08?1:0;
    const sbp=Math.round(112+(age-45)*.52+hypertension*17+(random()-.5)*22),dbp=Math.round(68+(random()-.5)*18),bmi=Number((23+(random()*9)+diabetes*2).toFixed(1));
    const totalCholesterol=Math.round(158+random()*95+smoker*12),hdl=Math.round(38+random()*34-(diabetes*4)),treatedBp=hypertension&&random()<.73?1:0;
    const afTrueRisk=Math.min(.78,Math.max(.01,.018+(age-45)*.008+diabetes*.055+hypertension*.07+heartFailure*.16+priorMi*.07));
    const ascvdTrueRisk=Math.min(.82,Math.max(.015,.02+(age-45)*.007+diabetes*.095+hypertension*.065+smoker*.095+priorMi*.13+(totalCholesterol-180)*.0008));
    const afOutcome=random()<afTrueRisk?1:0,ascvdOutcome=random()<ascvdTrueRisk?1:0,sexBias=sex==="Female"&&ageBand==="65-74"?-.13:sex==="Male"?.025:-.015;
    const ageNoise=ageBand==="75+"?(random()-.5)*.34:(random()-.5)*.16;
    const afScore=Math.min(.96,Math.max(.01,afTrueRisk+sexBias+ageNoise)),ascvdScore=Math.min(.96,Math.max(.01,ascvdTrueRisk+(sex==="Female"?-.045:.02)+(random()-.5)*.14));
    const nativeEnglish=random()<(sex==="Female"?.73:.81)?"Yes":"No";
    const deprivationQuintile=String(1+Math.floor(random()*5)),location=random()<.19?"Rural":"Urban";
    rows.push({patient_id:`SYN-${String(i+1).padStart(4,"0")}`,af_5yr_outcome:String(afOutcome),charge_af_risk:afScore.toFixed(4),ascvd_10yr_outcome:String(ascvdOutcome),pce_ascvd_risk:ascvdScore.toFixed(4),age:String(age),age_band:ageBand,sex,native_english:nativeEnglish,location,deprivation_quintile:deprivationQuintile,bmi:String(bmi),systolic_bp:String(sbp),diastolic_bp:String(dbp),total_cholesterol:String(totalCholesterol),hdl_cholesterol:String(hdl),smoker:smoker?"Yes":"No",diabetes:diabetes?"Yes":"No",hypertension:hypertension?"Yes":"No",bp_treatment:treatedBp?"Yes":"No",heart_failure:heartFailure?"Yes":"No",prior_mi:priorMi?"Yes":"No"});
  }
  return rows;
}

function PopulationProfile({rows,groupColumn,variable}:{rows:Row[];groupColumn:string;variable:string}){
  const numeric=rows.length>0&&rows.filter(row=>row[variable]!=="").every(row=>Number.isFinite(Number(row[variable]))),groups=[...new Set(rows.map(row=>row[groupColumn]||"Missing / unknown"))].sort();
  if(numeric){const values=rows.map(row=>Number(row[variable])),minimum=Math.min(...values),maximum=Math.max(...values),width=(maximum-minimum||1)/8,bins=Array.from({length:8},(_,i)=>({low:minimum+i*width,high:i===7?maximum:minimum+(i+1)*width}));return <div className="profile-chart">{groups.map((group,g)=><div className="profile-row" key={group}><strong>{group}</strong><div className="histogram">{bins.map((bin,i)=>{const groupRows=rows.filter(row=>(row[groupColumn]||"Missing / unknown")===group),count=groupRows.filter(row=>{const value=Number(row[variable]);return value>=bin.low&&(i===7?value<=bin.high:value<bin.high)}).length,share=groupRows.length?count/groupRows.length:0;return <div className="hist-bin" key={i} title={`${bin.low.toFixed(1)}–${bin.high.toFixed(1)}: ${(share*100).toFixed(1)}%`}><i style={{height:`${Math.max(2,share*240)}px`,background:COLORS[g%COLORS.length]}}/><span>{i%2===0?bin.low.toFixed(0):""}</span></div>})}</div></div>)}</div>}
  const categories=[...new Set(rows.map(row=>row[variable]||"Missing / unknown"))].sort();return <div className="profile-chart">{groups.map((group,g)=>{const groupRows=rows.filter(row=>(row[groupColumn]||"Missing / unknown")===group);return <div className="category-profile" key={group}><strong>{group}</strong>{categories.map(category=>{const share=groupRows.filter(row=>(row[variable]||"Missing / unknown")===category).length/groupRows.length;return <div className="category-bar" key={category}><span>{category}</span><div><i style={{width:`${share*100}%`,background:COLORS[g%COLORS.length]}}/></div><b>{pct(share)}</b></div>})}</div>})}</div>;
}

function parseCsv(text:string):Row[]{
  const records:string[][]=[]; let record:string[]=[],field="",quoted=false;
  for(let i=0;i<text.length;i+=1){const char=text[i]; if(char==='"'){if(quoted&&text[i+1]==='"'){field+='"';i+=1}else quoted=!quoted;} else if(char===","&&!quoted){record.push(field.trim());field="";} else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[i+1]==="\n")i+=1;record.push(field.trim());field="";if(record.some(Boolean))records.push(record);record=[];}else field+=char;}
  record.push(field.trim()); if(record.some(Boolean))records.push(record); if(records.length<2)throw new Error("The CSV needs a header and at least one data row.");
  const headers=records[0].map(h=>h.replace(/^\uFEFF/,"")); if(new Set(headers).size!==headers.length)throw new Error("Column names must be unique.");
  return records.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??""])));
}

function auc(scores:number[],outcomes:number[]){
  const pairs=scores.map((score,i)=>({score,outcome:outcomes[i]})).sort((a,b)=>a.score-b.score), positives=outcomes.reduce((s,v)=>s+v,0), negatives=outcomes.length-positives;
  if(!positives||!negatives)return null; let rankSum=0;
  for(let i=0;i<pairs.length;){let j=i+1;while(j<pairs.length&&pairs[j].score===pairs[i].score)j+=1;const rank=(i+1+j)/2;for(let k=i;k<j;k+=1)if(pairs[k].outcome===1)rankSum+=rank;i=j;}
  return (rankSum-positives*(positives+1)/2)/(positives*negatives);
}
function metricsFor(rows:Row[],groupColumn:string,secondGroup:string,outcomeColumn:string,scoreColumn:string,threshold:number):MetricRow[]{
  const buckets=new Map<string,Row[]>(); rows.forEach(row=>{const first=row[groupColumn]||"Missing / unknown",second=secondGroup?row[secondGroup]||"Missing / unknown":"",name=second?`${first} × ${second}`:first,bucket=buckets.get(name);if(bucket)bucket.push(row);else buckets.set(name,[row]);});
  return [...buckets.entries()].map(([group,groupRows])=>{const scores=groupRows.map(r=>Number(r[scoreColumn])),outcomes=groupRows.map(r=>Number(r[outcomeColumn]));let tp=0,tn=0,fp=0,fn=0;
    scores.forEach((score,i)=>{const prediction=score>=threshold?1:0;if(prediction&&outcomes[i])tp+=1;else if(prediction)fp+=1;else if(outcomes[i])fn+=1;else tn+=1;});
    const observed=outcomes.reduce((s,v)=>s+v,0)/groupRows.length,expected=scores.reduce((s,v)=>s+v,0)/groupRows.length;
    const sensitivity=tp+fn?tp/(tp+fn):null,specificity=tn+fp?tn/(tn+fp):null;
    return {group,n:groupRows.length,prevalence:observed,auc:auc(scores,outcomes),sensitivity,specificity,positiveRate:(tp+fp)/groupRows.length,brier:scores.reduce((s,v,i)=>s+(v-outcomes[i])**2,0)/groupRows.length,oeRatio:expected?observed/expected:null,ppv:tp+fp?tp/(tp+fp):null,npv:tn+fn?tn/(tn+fn):null,fpr:specificity==null?null:1-specificity,fnr:sensitivity==null?null:1-sensitivity};
  }).sort((a,b)=>a.group.localeCompare(b.group));
}
const pct=(value:number|null)=>value==null||!Number.isFinite(value)?"—":`${(value*100).toFixed(1)}%`; const dec=(value:number|null)=>value==null||!Number.isFinite(value)?"—":value.toFixed(2);

function MetricBars({data,metric,label,benchmark}:{data:MetricRow[];metric:keyof MetricRow;label:string;benchmark?:number}){
  return <div className="chart-card"><div className="chart-heading"><h3>{label}</h3><span>{benchmark?`Review below ${benchmark.toFixed(2)}`:"Higher is better"}</span></div><div className="bars">{data.map((row,index)=>{const suppressed=row.n<30,value=Number(row[metric]??0);return <div className="bar-row" key={row.group}><span className="bar-label">{row.group}</span><div className="bar-track"><div className="bar-fill" style={{width:suppressed?"0%":`${Math.max(2,value*100)}%`,background:COLORS[index%COLORS.length]}}/></div><strong>{suppressed?"Hidden":dec(value)}</strong></div>})}</div></div>;
}

export function FairnessWorkbench(){
  const initial=useMemo(()=>syntheticRows(),[]),[rows,setRows]=useState<Row[]>(initial),[fileName,setFileName]=useState("cardio_synthetic_demo.csv"),[outcomeColumn,setOutcomeColumn]=useState("af_5yr_outcome"),[scoreColumn,setScoreColumn]=useState("charge_af_risk"),[groupColumn,setGroupColumn]=useState("sex"),[secondGroup,setSecondGroup]=useState(""),[referenceGroup,setReferenceGroup]=useState("Male"),[comparisonGroup,setComparisonGroup]=useState("Female"),[profileVariable,setProfileVariable]=useState("age"),[threshold,setThreshold]=useState(.2),[error,setError]=useState(""),[showCsv,setShowCsv]=useState(false),[previewPage,setPreviewPage]=useState(0);
  const fileInput=useRef<HTMLInputElement>(null),columns=Object.keys(rows[0]??{}),sample=rows.slice(0,Math.min(rows.length,5000));
  const binaryColumns=columns.filter(column=>{const values=sample.map(row=>row[column]).filter(value=>value!=="");return values.length>0&&values.every(value=>value==="0"||value==="1")}),namedOutcomes=binaryColumns.filter(column=>/outcome|label|event|target/i.test(column)),outcomeColumns=namedOutcomes.length?namedOutcomes:binaryColumns;
  const allProbabilities=columns.filter(column=>{const values=sample.map(row=>row[column]).filter(value=>value!=="").map(Number);return values.length>0&&values.every(value=>Number.isFinite(value)&&value>=0&&value<=1)&&new Set(values).size>2}),namedProbabilities=allProbabilities.filter(column=>/score|risk|prob|prediction/i.test(column)),probabilityColumns=namedProbabilities.length?namedProbabilities:allProbabilities;
  const groupColumns=columns.filter(column=>column!=="patient_id"&&column!==outcomeColumn&&column!==scoreColumn&&!allProbabilities.includes(column)&&new Set(sample.map(row=>row[column]||"Missing / unknown")).size<=50);
  const validRows=rows.filter(row=>[0,1].includes(Number(row[outcomeColumn]))&&Number.isFinite(Number(row[scoreColumn]))&&Number(row[scoreColumn])>=0&&Number(row[scoreColumn])<=1);
  const data=useMemo(()=>metricsFor(validRows,groupColumn,secondGroup,outcomeColumn,scoreColumn,threshold),[validRows,groupColumn,secondGroup,outcomeColumn,scoreColumn,threshold]);
  const visibleData=data.filter(r=>r.n>=30),groupNames=data.map(r=>r.group);
  useEffect(()=>{if(!groupNames.includes(referenceGroup))setReferenceGroup(groupNames[0]??"");if(!groupNames.includes(comparisonGroup)||comparisonGroup===referenceGroup)setComparisonGroup(groupNames.find(name=>name!==referenceGroup)??groupNames[0]??"");},[groupNames.join("|"),referenceGroup,comparisonGroup]);
  const aucValues=visibleData.map(r=>r.auc).filter((v):v is number=>v!=null),bestAuc=aucValues.length?Math.max(...aucValues):NaN,worstAuc=aucValues.length?Math.min(...aucValues):NaN,positiveRates=visibleData.map(r=>r.positiveRate),maxPositive=positiveRates.length?Math.max(...positiveRates):NaN,minPositive=positiveRates.length?Math.min(...positiveRates):NaN,parityGap=maxPositive-minPositive;
  const sensitivityValues=visibleData.map(r=>r.sensitivity).filter((v):v is number=>v!=null),minSensitivity=sensitivityValues.length?Math.min(...sensitivityValues):NaN,maxSensitivity=sensitivityValues.length?Math.max(...sensitivityValues):NaN;
  const flagged=data.filter(r=>(r.auc!=null&&r.auc<.7)||(r.oeRatio!=null&&(r.oeRatio<.8||r.oeRatio>1.2))||r.n<30);
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{const parsed=parseCsv(await file.text()),next=Object.keys(parsed[0]),preview=parsed.slice(0,Math.min(parsed.length,5000)),binary=next.filter(column=>{const values=preview.map(row=>row[column]).filter(Boolean);return values.length>0&&values.every(value=>value==="0"||value==="1")}),namedBinary=binary.filter(n=>/outcome|label|event|target/i.test(n)),allProbability=next.filter(column=>{const values=preview.map(row=>row[column]).filter(Boolean).map(Number);return values.length>0&&values.every(value=>Number.isFinite(value)&&value>=0&&value<=1)&&new Set(values).size>2}),namedProbability=allProbability.filter(n=>/score|risk|prob|prediction/i.test(n)),selectedOutcome=(namedBinary.length?namedBinary:binary)[0],selectedProbability=(namedProbability.length?namedProbability:allProbability)[0],groups=next.filter(column=>column!=="patient_id"&&column!==selectedOutcome&&column!==selectedProbability&&!allProbability.includes(column)&&new Set(preview.map(row=>row[column]||"Missing / unknown")).size<=50);if(!selectedOutcome||!selectedProbability||!groups.length)throw new Error("The CSV needs a binary outcome, a 0–1 predicted probability, and a categorical fairness attribute.");setRows(parsed);setFileName(file.name);setError("");setOutcomeColumn(selectedOutcome);setScoreColumn(selectedProbability);setGroupColumn(groups.find(n=>/sex|gender|race|language|english|location|group|age_band/i.test(n))??groups[0]);setSecondGroup("");setProfileVariable(next.find(n=>/age|bmi|pressure|cholesterol/i.test(n))??next.find(n=>n!=="patient_id")??next[0]);setPreviewPage(0);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to read this CSV.");}}
  function resetDemo(){setRows(initial);setFileName("cardio_synthetic_demo.csv");setOutcomeColumn("af_5yr_outcome");setScoreColumn("charge_af_risk");setGroupColumn("sex");setSecondGroup("");setReferenceGroup("Male");setComparisonGroup("Female");setProfileVariable("age");setThreshold(.2);setError("");}
  function selectEndpoint(endpoint:"af"|"ascvd"){if(endpoint==="af"){setOutcomeColumn("af_5yr_outcome");setScoreColumn("charge_af_risk");setThreshold(.2)}else{setOutcomeColumn("ascvd_10yr_outcome");setScoreColumn("pce_ascvd_risk");setThreshold(.075)}}
  function downloadSample(){const headers=Object.keys(initial[0]),escape=(value:string)=>/[",\n]/.test(value)?`"${value.replaceAll('"','""')}"`:value,csv=[headers.join(","),...initial.map(row=>headers.map(header=>escape(row[header]??"")).join(","))].join("\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="cardio_risk_compass_sample.csv";anchor.click();URL.revokeObjectURL(url);}
  const disparity=bestAuc-worstAuc,previewRows=rows.slice(previewPage*25,previewPage*25+25),previewPages=Math.ceil(rows.length/25);
  const reference=data.find(r=>r.group===referenceGroup),comparison=data.find(r=>r.group===comparisonGroup),direction=(metric:keyof MetricRow)=>reference&&comparison&&typeof reference[metric]==="number"&&typeof comparison[metric]==="number"?Number(comparison[metric])-Number(reference[metric]):null;
  return <main>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">C</span><span>Cardio Risk Compass</span></a><nav><a href="#audit">Audit</a><a href="#findings">Findings</a><a href="#method">Method</a></nav><span className="research-badge">Research prototype</span></header>
    <section className="hero" id="top"><div><p className="eyebrow">Clinical model assurance · population-level analysis</p><h1>Find where a risk model <em>fails people.</em></h1><p className="hero-copy">Upload model outputs. Reveal subgroup performance and fairness gaps. Turn statistical evidence into clear, actionable review—before a model influences care.</p><div className="hero-actions"><button className="primary" onClick={()=>fileInput.current?.click()}>Upload patient-level CSV</button><button className="secondary" onClick={resetDemo}>Explore synthetic demo</button></div><p className="privacy-note">Runs in your browser. Uploaded data does not leave this page.</p></div><div className="hero-visual"><div className="pulse-line"/><div className="visual-card one"><span>Lowest sensitivity</span><strong>Women · 65–74</strong><b>−18.4 pts</b></div><div className="visual-card two"><span>Calibration review</span><strong>Older adults</strong><b>O:E 1.31</b></div><div className="visual-card three"><span>Audit status</span><strong>Action required</strong><i>3 signals</i></div></div></section>
    <section className="workspace" id="audit"><div className="section-intro"><div><p className="eyebrow">Fairness workbench</p><h2>Audit the evidence, not the average.</h2></div><p>Overall model quality can conceal clinically important subgroup failures. Configure the audit, then compare performance, calibration, and classification behavior.</p></div>
      <details className="csv-guide"><summary><span><b>New to the tool?</b> See the CSV structure and download an example</span><i>Open guide</i></summary><div className="csv-guide-body"><div><h3>Minimum required structure</h3><p>Each row represents one person or observation. Column names may differ—you map them below after upload.</p><table><thead><tr><th>Field type</th><th>Example</th><th>Requirement</th></tr></thead><tbody><tr><td>Observed outcome</td><td><code>af_5yr_outcome</code></td><td>Binary 0 or 1</td></tr><tr><td>Predicted probability</td><td><code>charge_af_risk</code></td><td>Number from 0 to 1</td></tr><tr><td>Fairness attribute</td><td><code>sex</code>, <code>native_english</code></td><td>At least two groups</td></tr><tr><td>Optional covariates</td><td><code>age</code>, <code>systolic_bp</code></td><td>Numeric or categorical</td></tr></tbody></table></div><div className="csv-example"><h3>Small example</h3><pre>patient_id,af_5yr_outcome,charge_af_risk,sex,native_english,age{`\n`}P001,1,0.42,Female,No,68{`\n`}P002,0,0.08,Male,Yes,54</pre><button className="primary" onClick={downloadSample}>Download full example CSV</button><p>Use de-identified data. Do not upload names, addresses, medical-record numbers, or other direct identifiers.</p></div></div></details>
      <div className="endpoint-switch"><div><span>Paper demonstration endpoints</span><strong>Select the clinical question</strong></div><button className={outcomeColumn==="af_5yr_outcome"?"active":""} onClick={()=>selectEndpoint("af")}><b>Atrial fibrillation</b><span>5-year outcome · CHARGE-AF risk model</span></button><button className={outcomeColumn==="ascvd_10yr_outcome"?"active":""} onClick={()=>selectEndpoint("ascvd")}><b>Atherosclerotic cardiovascular disease</b><span>10-year outcome · Pooled Cohort Equations</span></button></div>
      <div className="control-panel"><input ref={fileInput} className="sr-only" type="file" accept=".csv,text/csv" onChange={upload}/><div className="file-summary"><span className="file-icon">CSV</span><div><strong>{fileName}</strong><small>{rows.length.toLocaleString()} patients · {columns.length} columns · {validRows.length.toLocaleString()} valid for this analysis</small></div><button onClick={()=>setShowCsv(true)}>View data</button><button onClick={()=>fileInput.current?.click()}>Replace</button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="controls">
        <label>Observed binary outcome<select value={outcomeColumn} onChange={e=>setOutcomeColumn(e.target.value)}>{outcomeColumns.map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</select><small>Only columns containing 0/1 outcomes</small></label><label>Predicted probability<select value={scoreColumn} onChange={e=>setScoreColumn(e.target.value)}>{probabilityColumns.map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</select><small>Only numeric scores from 0 to 1</small></label><label>Fairness attribute<select value={groupColumn} onChange={e=>setGroupColumn(e.target.value)}>{groupColumns.map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</select><small>Categorical population fields</small></label><label>Intersection (optional)<select value={secondGroup} onChange={e=>setSecondGroup(e.target.value)}><option value="">None</option>{groupColumns.filter(c=>c!==groupColumn).map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</select><small>Optional second population field</small></label><label>Reference / privileged<select value={referenceGroup} onChange={e=>setReferenceGroup(e.target.value)}>{groupNames.map(c=><option key={c}>{c}</option>)}</select></label><label>Comparison / underprivileged<select value={comparisonGroup} onChange={e=>setComparisonGroup(e.target.value)}>{groupNames.filter(c=>c!==referenceGroup).map(c=><option key={c}>{c}</option>)}</select></label><label>Decision threshold <span>{threshold.toFixed(2)}</span><input type="range" min=".01" max=".8" step=".01" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><div className="direction-note"><strong>Direction</strong><span>comparison − reference</span></div>
      </div></div>
      <div className="profile-card"><div className="profile-heading"><div><p className="eyebrow">Population context</p><h3>Who is represented in each population?</h3><p>Compare covariate and outcome distributions before interpreting fairness metrics. Different case mix can explain part—but not necessarily all—of an observed gap.</p></div><label>Distribution to show<select value={profileVariable} onChange={e=>setProfileVariable(e.target.value)}>{columns.filter(c=>c!=="patient_id").map(c=><option key={c}>{c.replaceAll("_"," ")}</option>)}</select></label></div><PopulationProfile rows={rows} groupColumn={groupColumn} variable={profileVariable}/></div>
      <div className="comparison-strip"><div><span>Defined comparison</span><strong>{comparisonGroup||"Select comparison"} vs {referenceGroup||"Select reference"}</strong></div><div><span>Statistical parity difference</span><strong>{pct(direction("positiveRate"))}</strong></div><div><span>True-positive-rate difference</span><strong>{pct(direction("sensitivity"))}</strong></div><div><span>True-negative-rate difference</span><strong>{pct(direction("specificity"))}</strong></div></div>
      <div className="fairness-panel"><div className="fairness-panel-head"><div><p className="eyebrow">Directional fairness measures</p><h3>Comparison group minus reference group</h3></div><p>Zero means no measured difference. A difference is a review signal—not proof of discrimination. Interpret alongside prevalence, uncertainty, data quality, and clinical consequences.</p></div><div className="fairness-metrics">
        <article><span>Statistical parity difference</span><strong>{pct(direction("positiveRate"))}</strong><code>P(ŷ=1|comparison) − P(ŷ=1|reference)</code><p>Difference in how often groups are classified above the selected threshold.</p></article>
        <article><span>True-positive-rate difference</span><strong>{pct(direction("sensitivity"))}</strong><code>TPR comparison − TPR reference</code><p>Difference in sensitivity among people who experienced the outcome.</p></article>
        <article><span>True-negative-rate difference</span><strong>{pct(direction("specificity"))}</strong><code>TNR comparison − TNR reference</code><p>Difference in specificity among people who did not experience the outcome.</p></article>
        <article><span>False-positive-rate difference</span><strong>{pct(direction("fpr"))}</strong><code>FPR comparison − FPR reference</code><p>Difference in unnecessary positive flags among people without the outcome.</p></article>
        <article><span>False-negative-rate difference</span><strong>{pct(direction("fnr"))}</strong><code>FNR comparison − FNR reference</code><p>Difference in missed cases among people with the outcome.</p></article>
        <article><span>Positive predictive-value difference</span><strong>{pct(direction("ppv"))}</strong><code>PPV comparison − PPV reference</code><p>Difference in the reliability of a positive classification.</p></article>
        <article><span>Disparate-impact ratio</span><strong>{reference&&comparison&&reference.positiveRate?`${(comparison.positiveRate/reference.positiveRate).toFixed(2)}×`:"—"}</strong><code>positive rate comparison ÷ reference</code><p>Relative classification rate; 1.00 indicates parity.</p></article>
        <article><span>Equalized-odds gap</span><strong>{direction("sensitivity")!=null&&direction("fpr")!=null?pct(Math.max(Math.abs(direction("sensitivity")!),Math.abs(direction("fpr")!))):"—"}</strong><code>max(|TPR gap|, |FPR gap|)</code><p>Largest difference in error behavior across the two populations.</p></article>
        <article><span>Calibration O:E difference</span><strong>{dec(direction("oeRatio"))}</strong><code>O:E comparison − O:E reference</code><p>Difference between observed-to-expected outcome ratios.</p></article>
      </div></div>
      <div className="summary-grid"><article><span>Groups evaluated</span><strong>{data.length}</strong><small>{groupColumn.replaceAll("_"," ")}</small></article><article><span>AUC range</span><strong>{dec(worstAuc)}–{dec(bestAuc)}</strong><small className={disparity>.1?"warn":"good"}>{(disparity*100).toFixed(1)} point spread</small></article><article><span>Statistical parity gap</span><strong>{pct(parityGap)}</strong><small className={parityGap>.1?"warn":"good"}>Across positive rates</small></article><article><span>Groups requiring review</span><strong>{flagged.length}</strong><small className={flagged.length?"warn":"good"}>{flagged.length?"Performance or reliability signal":"No preset flags"}</small></article></div>
      <div className="charts-grid"><MetricBars data={data} metric="auc" label="Discrimination by subgroup (AUC)" benchmark={.7}/><MetricBars data={data} metric="sensitivity" label={`Sensitivity at ${(threshold*100).toFixed(0)}% threshold`}/></div>
      <div className="table-card"><div className="chart-heading"><h3>Complete subgroup audit</h3><span>Groups below n=30 are suppressed</span></div><div className="table-scroll"><table><thead><tr><th>Population</th><th>N</th><th>Prevalence</th><th>AUC</th><th>Sensitivity</th><th>Specificity</th><th>Positive rate</th><th>Brier</th><th>O:E ratio</th></tr></thead><tbody>{data.map((r,i)=>{const hidden=r.n<30;return <tr key={r.group}><td><span className="dot" style={{background:COLORS[i%COLORS.length]}}/>{r.group}{hidden&&<small className="suppressed"> Suppressed</small>}</td><td>{r.n}</td><td>{hidden?"—":pct(r.prevalence)}</td><td className={!hidden&&r.auc!=null&&r.auc<.7?"cell-warn":""}>{hidden?"—":dec(r.auc)}</td><td>{hidden?"—":pct(r.sensitivity)}</td><td>{hidden?"—":pct(r.specificity)}</td><td>{hidden?"—":pct(r.positiveRate)}</td><td>{hidden?"—":dec(r.brier)}</td><td className={!hidden&&r.oeRatio!=null&&(r.oeRatio<.8||r.oeRatio>1.2)?"cell-warn":""}>{hidden?"—":dec(r.oeRatio)}</td></tr>})}</tbody></table></div></div>
    </section>
    <section className="findings" id="findings"><div className="section-intro light"><div><p className="eyebrow">Clear-language interpretation</p><h2>What the numbers mean.</h2></div><p>Deterministic calculations drive every statement. Language support explains results without changing or inventing the underlying evidence.</p></div><div className="findings-layout"><article className="finding-primary"><span className="severity">Priority finding</span><h3>{comparisonGroup} is compared with the user-defined reference group, {referenceGroup}.</h3><p>The true-positive-rate difference is <strong>{pct(direction("sensitivity"))}</strong> and the statistical parity difference is <strong>{pct(direction("positiveRate"))}</strong>. Negative values mean the comparison group receives the outcome less often than the reference group; whether that represents unfairness requires prevalence, data-quality, and clinical context.</p><div className="evidence-line"><span>Definition</span><code>comparison − reference</code><code>n = {validRows.length}</code></div></article><div className="finding-stack"><article><span className="number">01</span><div><h3>Language is auditable</h3><p>Choose <code>native_english</code> to compare native-English and non-native-English populations. Missing or unknown language remains visible rather than being silently discarded.</p></div></article><article><span className="number">02</span><div><h3>Intersectional review</h3><p>Add a second attribute to examine combinations such as language × age, race × sex, or poverty × location.</p></div></article><article><span className="number">03</span><div><h3>Small-population protection</h3><p>Metrics for groups with fewer than 30 records are suppressed. Small event counts still require additional statistical review before conclusions are drawn.</p></div></article></div></div></section>
    <section className="mitigation"><div><p className="eyebrow">From finding to action</p><h2>Test safer alternatives.</h2><p>Fairness cannot be repaired with one switch. Choose and document experiments, then re-evaluate every metric because improving one measure may worsen another.</p></div><div className="action-grid"><article><span>01</span><h3>Recalibrate locally</h3><p>Fit calibration adjustments using representative local data, then compare observed-to-expected ratios.</p><button>Recommended first</button></article><article><span>02</span><h3>Review thresholds</h3><p>Test whether operating thresholds preserve clinically acceptable sensitivity and specificity.</p><button>Simulate impact</button></article><article><span>03</span><h3>Improve representation</h3><p>Assess missing predictors, sampling imbalance, and measurement differences before retraining.</p><button>Data review</button></article></div></section>
    <section className="method" id="method"><div><p className="eyebrow">Scientific foundation</p><h2>Built from published cardiovascular fairness research.</h2></div><blockquote>“Characterize and quantify the behavior of clinical risk models within specific subpopulations.”</blockquote><p>This prototype operationalizes metrics examined by Kartoun et al. in <em>Prediction performance and fairness heterogeneity in cardiovascular risk models</em>, Scientific Reports 12, 12542 (2022). It supports evaluation and governance; it is not a medical device.</p><a href="https://doi.org/10.1038/s41598-022-16615-3" target="_blank" rel="noreferrer">Read the open-access paper ↗</a></section>
    <footer><div className="brand"><span className="brand-mark">C</span><span>Cardio Risk Compass</span></div><p>A DBbun research prototype · Synthetic data · No patient data transmitted</p></footer>
    {showCsv&&<div className="data-modal" role="dialog" aria-modal="true" aria-label="CSV data viewer"><div className="data-dialog"><div className="data-dialog-head"><div><p className="eyebrow">CSV data viewer</p><h2>{fileName}</h2><span>{rows.length.toLocaleString()} patients · showing rows {(previewPage*25+1).toLocaleString()}–{Math.min((previewPage+1)*25,rows.length).toLocaleString()}</span></div><button onClick={()=>setShowCsv(false)} aria-label="Close data viewer">Close</button></div><div className="data-table"><table><thead><tr>{columns.map(column=><th key={column}>{column.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{previewRows.map((row,index)=><tr key={previewPage*25+index}>{columns.map(column=><td key={column}>{row[column]||<em>missing</em>}</td>)}</tr>)}</tbody></table></div><div className="data-pager"><button disabled={previewPage===0} onClick={()=>setPreviewPage(page=>Math.max(0,page-1))}>Previous 25</button><span>Page {(previewPage+1).toLocaleString()} of {previewPages.toLocaleString()}</span><button disabled={previewPage>=previewPages-1} onClick={()=>setPreviewPage(page=>Math.min(previewPages-1,page+1))}>Next 25</button><button onClick={downloadSample}>Download sample CSV</button></div></div></div>}
  </main>;
}
